"""
Adapter for bare USB-RS485 interfaces with no onboard framing microcontroller.

Unlike Enttec widgets, these interfaces have no onboard framing
microcontroller - RDM/DMX bytes go directly on the wire with no wrapper
protocol. The BREAK/MAB signal that normally precedes each DMX/RDM frame is
generated by the host toggling the UART's break condition instead (see
`requires_manual_break` and `AsyncSerialTransport._tx_loop`).
"""

import logging

from serial import EIGHTBITS, PARITY_NONE, STOPBITS_TWO

from ...protocols.manchester_codec import find_discovery_frame_length
from ..interface_adapter import InterfaceAdapter, InterfaceType, SerialConfig

logger = logging.getLogger(__name__)

_SC_RDM = 0xCC
_SC_DMX = 0x00


class BareUsbRs485Adapter(InterfaceAdapter):
    """
    Adapter for bare USB-RS485 interfaces (FTDI FT232R-based) with no
    onboard framing microcontroller.

    No message wrapper: RDM requests/responses and DMX frames are sent and
    received as raw bytes with their own start codes, exactly as they appear
    on the DMX/RDM wire.
    """

    USB_STR_DESC = "FT232R USB UART"

    def __init__(self, port: str):
        """
        Initialize the adapter.

        Args:
            port: COM port (e.g., "COM7" on Windows, "/dev/ttyUSB0" on Linux)
        """
        self._port = port

    @property
    def serial_config(self) -> SerialConfig:
        """DMX512-A requires 250000 baud, 8 data bits, no parity, 2 stop bits (8N2)."""
        return SerialConfig(
            port=self._port,
            baudrate=250000,
            bytesize=EIGHTBITS,
            parity=PARITY_NONE,
            stopbits=STOPBITS_TWO,
        )

    @property
    def interface_type(self) -> InterfaceType:
        """Return this adapter's interface identifier."""
        return InterfaceType.BARE_USB_RS485

    @property
    def requires_manual_break(self) -> bool:
        """This interface has no onboard BREAK/MAB generator - the host must toggle it."""
        return True

    def frame_rdm_request(self, rdm_data: bytes, port: int = 1) -> bytes:
        """No wrapper - the already-encoded RDM packet goes straight on the wire."""
        return rdm_data

    def frame_rdm_discovery_request(self, rdm_data: bytes, port: int = 1) -> bytes:
        """Same as regular request - no wrapper distinguishes discovery frames."""
        return rdm_data

    def frame_dmx_output(self, dmx_data: bytes, port: int = 1) -> bytes:
        """Prefix with the DMX start code; no wrapper."""
        return bytes([_SC_DMX]) + dmx_data

    def parse_rdm_response(self, raw_data: bytes) -> bytes | None:
        """Extract exactly one complete frame's worth of bytes, as-is."""
        frame_len = self.find_frame_length(raw_data)
        return bytes(raw_data[:frame_len]) if frame_len > 0 else None

    def find_frame_length(self, buffer: bytes) -> int:
        """
        Determine frame length for raw wire data: either a DISC_UNIQUE_BRANCH
        Manchester response (starts with 0xFE) or a standard RDM response
        (starts with 0xCC, whose byte[2] is the E1.20 "Message Length" field
        counted from the start code through the last parameter data byte -
        total frame length is that value plus 2 checksum bytes).
        """
        if not buffer:
            return 0

        if buffer[0] == 0xFE:
            return find_discovery_frame_length(buffer)

        if buffer[0] == _SC_RDM:
            if len(buffer) < 3:
                return 0  # not enough bytes to read the message-length field yet
            total = buffer[2] + 2
            return total if len(buffer) >= total else 0

        return 0  # unrecognized leading byte - let FrameBuffer resync past it
